// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhX_KE8CimOuyj0w6LdlDevlEBY93rJEk',
    appId: '1:79359522113:web:aebc1bc0ea09e82b085dc0',
    messagingSenderId: '79359522113',
    projectId: 'shishu-ghar-2024',
    authDomain: 'shishu-ghar-2024.firebaseapp.com',
    storageBucket: 'shishu-ghar-2024.appspot.com',
    measurementId: 'G-1K1RKXBZYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbxHXhy3Cob1dG4C3lZcOaJhMwh539wZ8',
    appId: '1:676418521646:android:969db8e8281f4e4052edbf',
    messagingSenderId: '676418521646',
    projectId: 'notifications-demo-e45f7',
    storageBucket: 'notifications-demo-e45f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvPV6U2hpSX2aDUR9jseXysBItBOJLs9A',
    appId: '1:79359522113:ios:8c292b357ca5bcd5085dc0',
    messagingSenderId: '79359522113',
    projectId: 'shishu-ghar-2024',
    storageBucket: 'shishu-ghar-2024.appspot.com',
    iosBundleId: 'com.example.shishughar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvPV6U2hpSX2aDUR9jseXysBItBOJLs9A',
    appId: '1:79359522113:ios:8c292b357ca5bcd5085dc0',
    messagingSenderId: '79359522113',
    projectId: 'shishu-ghar-2024',
    storageBucket: 'shishu-ghar-2024.appspot.com',
    iosBundleId: 'com.example.shishughar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhX_KE8CimOuyj0w6LdlDevlEBY93rJEk',
    appId: '1:79359522113:web:4fb326a676ce75f5085dc0',
    messagingSenderId: '79359522113',
    projectId: 'shishu-ghar-2024',
    authDomain: 'shishu-ghar-2024.firebaseapp.com',
    storageBucket: 'shishu-ghar-2024.appspot.com',
    measurementId: 'G-5HB4VSFVM5',
  );

}