class CustomText {
  static String Dob = "DOB";

  static String SHISHUGHAR = "SHISHU GHAR";
  static String ShishuGhar = "Shishu Ghar";
  static String hindiSHISHUGHAR = "शिशु गृह";
  static String SishuGharManagementSystem = "Shishu Ghar Management System";
  static String English = "English";
  static String Hindi = "हिंदी";
  static String Date = "Date : ";
  static String DateS = "Date";
  static String MajorTopic = "Major Topic";
  static String AttenList = "Attendance List";
  static String amount = "Amount";
  static String Odiya = "ଓଡିଆ";
  static String MobileNo = "Mobile No";
  static String DateOfExit = 'Date of Exit';
  static String ReasForExit = 'Reason for Exit';
  static String AgeOnDayOfExit = 'Age on the day of exit';
  static String VisitNotes = "Visit Notes";
  static String year = "Year";
  static String itemRefresh = "itemRefresh";
  static String population = "Population";
  static String quarter = "Quarter";
  static String VisitNote = "Visit Note";
  static String villageProfile = "Village Profile";
  static String villageCode = "Village Code";
  static String villageName = "Village Name";
  static String villageList = 'Village List';
  static String GrowthMonitoring = "Growth Monitoring";
  static String GrowthChart = "Growth Chart";
  static String Attendance = "Attendance";
  static String CrecheCommittee = "Creche Committee";
  static String GrievanceIssuTracking = "Grievance & Issue Tracking";
  static String VisitOn = "Visit On : ";
  static String Creche = "Creche : ";
  static String Creches = "Creche";
  static String Creches_ = "Creches";
  static String Password = "Password";
  static String Rollout = "Rollout";
  static String TrainingMeeting = "Training & Meeting";
  static String ShishuGharDetails = "Shishu Ghar Details";
  static String RequisitionReceipts = "Requisition & Receipts";
  static String Cashbook = "Cashbook";
  static String LogIn = "Login";
  static String Save = "Save";
  static String SaveNext = "Save & Next";
  static String Selecthere = "Select here";
  static String typehere = "Type here";
  static String Home = "Home";
  static String DetailsChild = "Details of Child";
  static String attenAlredyExist =
      "An attendance already exists for the selected Date";
  static String BasicInformation = "Basic Information";
  static String VisitInformation = "Visit Information";
  static String ForgotPassword = "Forgot your Password?";
  static String Name = "Name : ";
  static String Name_ = "Name";
  static String Gender = "Gender";
  static String Month = "Month";
  static String Year = "Year";
  static String Profile = "Profile : ";
  static String ProfileS = "Profile";
  static String Resources = "Resources";
  static String Trackchild =
      "Track your child's daily health and wellness progress";
  static String Activities = "Activities";
  static String NewTask = "Task & Activities Awaiting Your Inputs";
  static String FollowUps = "Follow-Ups";
  static String PendingRed = "Red Flag Follow-ups";
  static String Enrolledchildren = "Children Enrolled";
  static String Enrolled = "Enrolled";
  static String Enroll = "Enroll";
  static String NotEnroll = "not_enrolled";
  static String Dashboard = "Dashboard";
  static String Reports = "Reports";
  static String Report = "Report";
  static String DashBoardReport = "Dashboard Report";
  static String More = "More";
  static String District = "District";
  static String Block = "Block";
  static String State = "State";
  static String Districts = "District : ";
  static String Blocks = "Block : ";
  static String GramPanchayat = "Gram Panchayat";
  static String Village = "Village";
  static String BalanceAmount = "Balance amount";
  static String HamletPadanearest = "Hamlet/Padanearest";
  static String Landmark = "Landmark";
  static String NameofRespondent = "Name of Respondent";
  static String NameofChild = "Name of Child";
  static String RelationshipChild = "Relationship with Child";
  static String AgeofRespondent = "Age of Respondent";
  static String AgeofRespondents = "Age of Respondent : ";
  static String SocialCategory = "Social Category";
  static String Adultabove18 = "Adult (above 18)";
  static String Children618 = "Children (6-18)";
  static String Children36 = "Children (3-6)";
  static String Children3 = "Children (<3)";
  static String FamilyMember = "No. of Family Member";
  static String Male = "Male";
  static String Female = "Female";
  static String Filter = "Filter";
  static String Transgender = "Transgender";
  static String PrimaryOccupation = "Primary Occupation";
  static String nonAgriculture = "Casual Labour\nin Non Agriculture";
  static String SelfEmployed = "Self Employed";
  static String Agriculture = "Wage Labour\nin Agriculture";
  static String Farming = "Farming";
  static String OtherSpecified = "Other\nSpecified";
  static String Yes = "Yes";
  static String No = "No";
  static String HHhead = "HH Head : ";
  static String Pvtg = "Is the Family is PVTG?";
  static String HouseholdListing = "Household Listing";
  static String AddHouseholdListing = "Add Household";
  static String AddHouseholdListingChild = "Add Child Household";
  static String AddVisitnote = "Add Visit Note";
  static String add = "Add";
  static String BirthAvailable = "Date of Birth Available?";
  static String LineListedHouseholds = "HH List";
  static String Search = "Search";
  static String NameRespondent = "Name of Respondent : ";
  static String Villages = "Village : ";
  static String ChildrenUnderYears = "Children Under 3 Years: ";
  static String TotalChildrenenrolled = "Total Children enrolled: ";
  static String PendingSync = "Pending\nSync";
  static String PendingVerification = "Pending\nVerification";
  static String Sync = "Sync";
  static String Verify = "Verify";
  static String VerifyData = "Verify Data";
  static String ChildEnrollment = "Child Enrollment";
  static String Childattendance = "Child Attendance";
  static String ChildId = "Child ID";
  static String ChildName = "Child Name";
  static String ChildCareName = "Child Care Name";
  static String ChildPicture = "Add Picture";
  static String ChildProfile = "Child Profile";
  static String CrecheCaregiver = "Creche Caregiver";
  static String DOB = "Date of Birth";
  static String Nomination = "Nomination Time";
  static String NominationDate = "Nomination Date";
  static String PresentBreastFeeding = "In Present She/he Breast Feeding";
  static String PhysicallyNotFit = "Is Child Physically Not Fit";
  static String MedicalIssue = "Is Child Has Any Medical Issue  (last 6 Month)";
  static String childInfoNotAvailable = "Child information is not available";
  static String Clarify = "If Any (Clarify)";
  static String howManySiblingsArChildhave = "how Many Siblings Are Child have";
  static String Daily = "Daily : ";
  static String Monthly = "Monthly : ";
  static String Children = "Children : ";
  static String Childrens = "Children";
  static String Caregiver = "Caregiver : ";
  static String Submitedon = "Submited on : ";
  static String AddDailyAttendance = "Add Daily Attendance";
  static String ShishuGharclosed =
      "Select, If Shishu Ghar is Closed for the Day";
  static String Status = "Status";
  static String Reasonforclosure =
      "Reason for Closure (Show based on response)";
  static String OpenTime = "Open Time :    ";
  static String closeTime = "Closing Time : ";
  static String EntryTime = "Entry Time";
  static String ExitTime = "Exit Time";
  static String Hours = "Hours";
  static String Minutes = "Minutes";
  static String NumberofChildrenServed = "Number of Children Served";
  static String NameofEnrolledChildren = "Name of Enrolled Children";
  static String Lunch = "Lunch";
  static String Breakfast = "Breakfast";
  static String EveningSnacks = "Evening Snacks";
  static String Egg = "Egg      ";
  static String LoginwithOTP = "Login with OTP";
  static String back = "Back";
  static String Next = "Next";
  static String enrolled = "Enrolled";
  static String HHprofile = "HH Profile";
  static String HHchildrenListing = "HH List Children";
  static String LastMeasurement = "Last Measurement";
  static String OTPVerification = "OTP Verification";
  // static String receivedcode = "Didn’t received code? ";
  static String Resend = "Resend";
  static String verificationcode = "Enter the verification code";
  static String Createnewpassword = "Set New Password";
  static String email = "Email";
  static String mobileNumber = "Mobile Number";
  static String Newpasswordmustbeunique =
      "Your new password must be unique from those previously used.";
  static String resetpassword = "Reset Password";
  static String NewPassword = "New Password";
  static String confirmPassword = "Confirm Password";
  static String ChildIddot = "Child ID : ";
  static String ChildNamedot = "Child Name : ";
  static String MotherName = "Mother Name : ";
  static String Age = "Age : ";
  static String Genderdot = "Gender : ";
  static String CrecheName = "Creche Name";
  static String ChildNo = "Child No : ";
  static String CrecheProfileView = "Creche Profile";
  static String childAttendence = "Child Attendance";
  static String checkIns = "Check in";
  static String checkInsCrech = "Creche Check In";
  static String UserName = "Username";
  static String Email = "Email/Mobile Number";
  static String sync = "Synchronization";
  static String downloadtemplets = "Download Template";
  static String location = "Location";
  static String Setlocation = "Set Location";
  static String checkIN = "Check In";
  static String checkInAs = "Check in at";
  static String state = "State";

  static String hh_detail = "HH Detail";
  static String ok = "Ok";
  static String PrivacyPolicy = "Privacy Policy";
  static String PrivacyPolicyDescription = "Privacy Policy Description";
  static String pleaseSelectChildrenForAttendence =
      "Please Select Children For Attendance";
  static String nointernetconnectionavailable =
      "No internet connection available";
  static String datevisit = "Date of Visit";
  static String dateCheckin = "Date of Check In";
  static String DateofAttendance = "Date of Attendance";
  static String relationshipwithchild = "Relationship with child : ";
  static String ageInMonth = "Child age (In Months)";
  static String Pendingsync = "Pending sync";
  static String sta_tus = "Status : ";
  static String imageFiles = "Image File";
  static String hhName = "House hold name : ";
  static String hhNameS = "HH name";
  static String NorecordAvailable = "No record available";
  static String recordAvailable = "record available for upload";
  static String recordsAvailable = "records available for upload";
  static String HHListing = "HH Listing";
  static String SelectVillage = "Select Village";
  static String geoWiDownDwnload = "Geography wise Download data";
  static String downloadData = "Download data";
  static String Cancel = "Cancel";
  static String ChildAlredExitSelectValidDAte = "This child has already exited Please select a date before exit date";
  static String IAgree = "I Agree";
  static String StartDate = "Start Date";
  static String EndDate = "End Date";
  static String plSelect_state = "Please select state";
  static String plSelect_district = "Please select district";
  static String plSelect_block = "Please select block";
  static String plSelect_geamPanchayat = "Please select gram panchayat";
  static String plSelect_village = "Please select village";
  static String plSelect_creche = "Please select creche";
  static String data_downloaded_successfully = "Data downloaded successfully.";
  static String nothing_for_download = "Nothing for download";
  static String master_data_download = "Master data downloaded!";
  static String do_you_want_to_download = "Do you want to Download?";
  static String do_you_want_to_upload = "Do you want to upload?";
  static String data_upload_success_msg = "Data Uploaded Successfully";
  static String nothing_for_upload_msg = "Nothing for upload";
  static String pleaseSelectMonth = "Please select a month";
  static String pleaseUploadDataFirst = "Please upload pending data first.";
  static String darftDataForComplete =
      "You have uncompleted data in your device, please complete and upload first and then try to download data.";

  static String darftDataForLogoyt =
      "You have draft data in your device, please complete and upload first then try to logout.";

  static String change_language_text = "Change Language";
  static String moneyRecevied = "Money Received by Creche Caregiver?";
  static String Generalfilter = "General Filter";
  static String Locationfilter = "Location Filter";
  static String Pendingforverify = "Pending for verify";
  static String FlaggedChilderen = "Flagged Children";
  static String ChildReffrel = "Child Referral";
  static String ChilderenExistingshishuGhar = "Childeren Existing shishu Ghar";
  static String data_not_uploaded_msg = "Data not uploaded.";
  static String columnBreak = 'Column Break';
  static String BENEFICIARYCONSENTFORM = 'BENEFICIARY CONSENT FORM';
  static String tabBreak = 'Tab Break';
  static String plsFilManForm = "Please fill all mandatory fields!";
  static String dataSaveSuc = "Data saved successfully";
  static String Caregiver_Name = 'Caregiver Name';
  static String Caregiver_Code = 'Caregiver Code';
  static String Caregiver_name = "Caregiver Name : ";
  static String requiredField = "Required field ";
  static String oldPassword = "Old password";
  static String oldpasswordRequred = "Old password required";
  static String oldpasswordisNotMatch = "Old password is incorrect";
  static String newPasswordRequred = "New password required";
  static String confromPasswordRequred = "Confirm password required";
  static String oldAndNewPassword = "old and new password can not be same";
  static String newAndConfrom = "New and confirm password must be same";
  static String requiredColon = "required:";
  static String required = "Required";
  static String masterData = "Master data";
  static String uploadData = 'Upload data';
  static String valueColon = "value:";
  static String crecheCaregiver = 'Creche Caregiver';
  static String careGiverName = 'Primary caregiver name';
  static String DoUwntToSv = 'Do you want to Save?';
  static String Is_Active = 'Is Active';
  static String selecItemNull = "selected items is null";
  static String sectionBreak = 'Section Break';
  static String CrecheId = "Creche ID";
  static String Creche_Name = 'Creche Name';
  static String Submit = 'Submit';
  static String somethingWentError = 'Something went error';
  static String selectVerifyStatus = 'Select Verify status';
  static String statusUpdateSuccssFully = 'Status Update SuccessFully';
  static String EmailAddress = "Email Address";
  static String Newemailmustbeunique =
      "Enter Your Email-Address and received an link for reset password.";
  static String logoutMsg = "Are you sure you want to logout?";
  static String endDateMsg = "End date should be after start date.";
  static String startDateMsg = "Start date should be before end date.";
  static String error = "Error";
  static String pleaseWait = "Please wait..";
  static String uploadingPleaseWait = "Uploading please wait";
  static String pleaseSelectStartDate = "Please select start date";
  static String token_expired = "Token expired. Please logout & login again.";
  static String passwordChangeSuccfull = "Password Changed SuccessFully";
  static String passwordChangeNoChanges = "Password not changed.";
  static String pleaseselectcrechefirst = "Please select creche first.";
  static String pleaseFillMeasurementDate = "Please select measurement date";
  static String MyProfile = "My Profile";
  static String ChangePassword = "Change Password";
  static String Logout = "Logout";
  static String Version = "Version";
  static String child_exited = "Exited";
  static String HealthUpdate = "Health Update";
  static String EvventUpdate = "Event Update";
  static String SelectOneoption = "Select one for image!";
  static String Camera = "Camera";
  static String totalHH = "Total HH";
  static String Gallery = "Gallery";
  static String saveEnrolled = "Save & Enrolled";
  static String Verification_status = "Verification status";

  static String Supervisor = "Supervisor";
  static String Opened_On = "Opened On";
  static String enrolled_children = "Enrolled Children";
  static String anthropomertry = "Anthropometry";
  static String anthropomertryDetails = "Anthropometry Details";
  static String child_exit = "Child Exit";
  static String creche_committee_meeting = "Creche Committee Meeting";
  static String creche_enrollement = "Creche Enrollment";
  static String Stock = "Stock";
  static String Task = "Task";
  static String ShishuGharList = "Shishu ghar listing";
  static String Address = "Address";
  static String Location = "Location";
  static String hhHeadName = "HH Head name";
  static String hhID = "HH ID";
  static String Plsselecimgoption = "Please select an option";
  static String Add_Attendance = 'Add Attendance';
  static String Attendance_Children = 'Attendance Children';
  static String childrenCountVallidattion =
      'No. of children cannot not be greater than the children present';
  static String age = 'Age';
  static String ageInMonthEn = 'Age (In Months)';
  static String DontHaveChildrenForAttender = 'Please enroll child first';
  static String DontHaveChildrenForAnthropometry = 'Please enroll child first';
  static String ChildEnrollsuccess = "Child enrolled successfully";
  static String zScrore = "Z - Score";
  // static String Attendance = "Attendance";

  static String eventALredyExistd =
      "An event already exists for the selected Date";
  static String detail = "Details";
  static String WeightforHeight = 'Weight for height';
  static String Moderate = 'Moderate';
  static String WeightforAge = 'Weight for age';
  static String Normal = 'Normal';
  static String HeightforAge = 'Height for Age';
  static String Severe = "Severe";
  static String illness = "illness";
  static String ChildHealthDetail = "Health Detail";
  static String ChildImmunizationDetails = "Immunization";
  static String ChildEventDetail = "Event Detail";
  static String Grievance = "Grievance";
  static String IssueSubmit = "Issue Submit";
  static String ChildDetails = "Child Details";
  static String DateofEnrollement = "Date of Enrollment";
  static String ChildHealth = "Child Health";
  static String ChildEvents = "Child Event";
  static String ChildExit = "Child Exit";
  static String VaccinationDetails = "Vaccination Details";
  static String ImmunizationList = "Immunization List";
  static String ChildImmunization = "Child Immunization";
  static String Vaccines = "Vaccines";
  static String VaccineName = "Vaccine Name";
  static String SiteForVaccinations = "Site For Vaccinations";
  static String ChildGrievances = "Grievance";
  static String markAllPresent = 'Mark all Present';
  static String overdue = "Overdue";
  static String complted = "Completed";
  static String upcomming = "Upcoming";
  static String childAgeInDays = "Child age in days";
  static String childAgeInDaysbrac = "Child age (in days)";
  static String vaccinationDate = "Vaccination Date";
  static String Vaccinated = "Vaccinated";
  static String vaccine = "Vaccine";
  static String sideForVaccination = "Site of vaccination";
  static String selectVacinationDate = "Select vaccination date.";
  static String selectVaccinated = "Please select vaccinated?";
  static String logoutPendingDataMsg =
      "You have un-synced data in your device, please upload first and then try to logout.";
  static String CrecheMonitor = "Creche Monitor";
  static String CrecheMonitoring = "Creche Monitoring";
  static String CrecheMonitorList = "Creche Monitor List";
  static String Alm = "Account and logistics management";
  static String Cbm = "Capacity building manager";
  static String childReferral = "Child Referral";
  static String minAgeInMonthEn = 'Min Age (In Months)';
  static String maxAgeInMonthEn = 'Max Age (In Months)';
  static String followUpChildList = 'FollowUp Child List';
  static String FollowUpDetail = 'Follow Up Detail';
  static String fllowUp = 'Follow up';
  static String dateOfReffrel = 'Date Of Referral';
  static String schduleDate = 'Scheduled Date';
  static String measurementDate = 'Measurement Date';
  static String SubOn = "Submitted on";
  static String schduleed = 'Scheduled';
  static String followup_visit_date = 'Followup Visit Date';
  static String TotalChildren = 'Total Child';
  static String MeasuredChildren = 'Measured Children';
  static String PresChild = "Present Children";
  static String measurment = 'Measurement';
  static String selectAllForUpload = 'Select all for upload';
  static String selectAll = 'Select all';
  static String uploadAll = 'Upload All';
  static String ccListing = "Creche Committee Listing";
  static String CrecheCommitte = "Creche Committee";
  static String ccDetails = "Meeting Details";
  static String height = "Height (in cm)";
  static String weight = "Weight (in kg)";
  static String CBM = "CBM";
  static String ALM = "ALM";
  static String uploadChildMsg = "Please upload child profile first.";
  static String childUpdatedSucces = "Child updated successfully";
  static String CashBookReceipt = "CashBook Receipt";
  static String CashBookExpences = "CashBook Expenses";
  static String Expenses = "Expenses";
  static String Receipt = "Receipt";
  static String CashBookDeat = "CashBook Detail";
  static String CashbookList = "Cashbooks List";
  static String languages = "Language";
  static String userMannual = "User Manual";
  static String appInfo = "App Info";
  static String ticketSupport = "Ticket Support";
  static String clear = "Clear";
  static String select_here = "Select Here";
  static String entryTime = "Entry Time";
  static String exitTime = "Exit Time";
  static String demographicalDetails = "Demographical Details";
  static String EnrolledChild = "Enrolled Child";
  static String Description = "Description";
  static String DischangeDate = "Discharge Date";
  static String AdmissionDate = "Admission date";
  static String visitDate = "Visit date";
  static String GrievanceCategory = "Grievance Category";
  static String RespondentName = "Respondent Name";
  static String HHlist = "HH list";
  static String growthMonitoring = "You can not modify this growth monitoring";
  static String VisitPurpose = "Visit purpose";
  static String UpdateLocation = "Update Location";
  static String role = "Role";
  static String exit = "Exit";
  static String enrolledChild = "Enrolled Child";
  static String symptoms = "Symptoms";
  static String actionTaken = "Action Taken";
  static String boy = "Boy";
  static String girl = "Girl";
  static String other = "Other";
  static String visitNoteAlrdyExists =
      "A Visit Note already exists for the selected Date";
  static String enrollExitChild = "Child Enrollment and Exit";
  static String requisition = "Requisition";
  static String stockDetails = "Stock Detail";
  static String requiDetails = "Requisition Detail";
  static String stockList = "Stock List";
  static String requiList = "Requisition List";
  static String addAttendance = "Please add attendance for the month first";
  static String noItemsAvail = "No Items Available";
  static String dbBackup = "Database Backup";
  static String childExited = "Child Exited Successfully";
  static String unsynched = "Unsynched";
  static String childCount = 'Total Child';
  static String attendanceCount = "Total Attendance";
  static String childPresent = "Child Present";
  static String exitedChildCount = "Exited Child Count";
  static String crecheSupervisor = "Creche Supervisor";
  static String clusterCoordinator = "Cluster Coordinator";
  static String alm = "Accounts and Logistics Manager";
  static String cbm = "Capacity and Building Manager";
  static String uploading = "Uploading";
  static String noEnrolledChild = "No enrolled child available for this date";
  static String all = "All";

  static String usynchedAndDraft = "Unsynched and Darft";
  static String selectItemForAdd = "Please select an item";

  static String ageInDays = "Child age (In Days)";
  static String geoGraphyIsNotAssign =
      "Geography is not assigned. Contact your system administrator.";
  static String requiCannotBeMadeYet =
      "Requisitions for the current year cannot be made yet";
  static String locationNotAvailable =
      "Location is not available at the moment";
  static String areSureToDelete = "Are you sure you want to delete this record";
  static String delete = "Delete";
  static String updateDoctype = "Update Doctype";
  static String deviceChangeMsg = 'deviceChangeMsg';
  static String login = 'Log In';
  static String downloadFiyrst = "Please download data first";
  static String doctypeUpdated = "Doctype updated successfully";
  static String childDarftMsg = 'Child is in Draft please complete first';
  static String shouldExit = "Are you sure want to the exit this screen";
  static String childDobIsNotValidForEnrolled =
      "Child dob is not valid for enrolled.";
  static String crecheOpeningDateMsg =
      "Creche opening date not available please contact your admin.";
  static String crecheOpeningDateNotMatchMsg =
      "Enrollment date can not be before then creche opening date.";
  static String crecheOpeningDateAfterDate =
      "Enrollment can not  be after then after creche closing date";
  static String crecheClosingDateMsg =
      "Creche closed enrollment can not be done.";

  static String crecheNotopenBefore =
      "Enrolment cannot be done before the creche opening date.";

  static String crecheUpdateInHH =
      "Creche can not be changed as there are active children in the current creche.";

  static String freshChild = "Fresh child";
  static String exitedChild = "Exited child";
  static String removedItem = "Removed Item List";
  static String noREmovedItem = "No removed item";
  static String mismatched = "Mismatch";
  static String received = "Received";
  static String plsFillLessOrEqual = "Please enter amount less than or equal";
  static String supplied = "Supplied";
  static String opening = "Opening";
  static String wstage = "Wastage";
  static String closing = "Closing";
  static String usage = "Usage";
  static String locationNotCaptured = "Location is not captured. Please try again.";
  static String serviceNotEnabled = "Service Not Enabled";
  static String permissionrequired = "Permission Required";
  static String allowPermission = "Please allow location permission";
  static String setting = "Settings";
  static String crecheNotAvailable = "Creche is not available please contact to admin.";


  /* DOCTYPE LIST*/
  static String childGrowthMonitoring = "Child Growth Monitoring"; //0
  static String AnthroData = "Anthropromatic Data"; //1
  static String creche = "Creche"; //2
  static String crceheCaregiver = "Creche Caregiver"; //3
  static String village = "Village"; //4
  static String demographicalDetail = "Demographic Details"; //5
  static String cashbookReceipt = "Cashbook Receipt"; //6
  static String crecheStock = "Creche Stock"; //7
  static String formLogic = "Forms Logic"; //8
  static String crecheRequisiton = "Creche Requisition"; //9
  static String childProfileDoctype = "Child Profile"; //10
  static String requisitionChildTable = "Requisition Child table"; //11
  static String cmcCCDoctype = "Creche Monitoring Checklist CC"; //12
  static String childEnrollExit = "Child Enrollment and Exit"; //13
  static String grievienceDoctype = "Grievance"; //14
  static String cmcCBMDoxtype = "Creche Monitoring Checklist CBM"; //15
  static String cmcDoctype = "Creche Monitoring Checklist"; //16
  static String crecheMeeting = "Creche Committee Meeting"; //17
  static String cmcALMDoctype = "Creche Monitoring Checklist ALM"; //18
  static String childAttendance = "Child Attendance"; //19
  static String cashbook = "Cashbook"; //20
  static String childFollowUp = "Child Follow up"; //21
  static String childExit = "Child Exit"; //22
  static String childreferralDoctype = "Child Referral"; //23
  static String childHealthDoctype = "Child Health"; //24
  static String houseHoldChildForm = "Household Child Form"; //25
  static String houseHoldForm = "Household Form"; //26
  static String childEventDoctype = "Child Event"; //27
  static String childImmunization = "Child Immunization"; //28
  static String anyMedical = "Any Medical Compliction"; //29
  static String crceheCheckIn = "Creche Check In"; //30
  static String visitPurpose = "Visit Purpose child table"; //31
  static String disability = "Disability"; //32
  /* DOCTYLE LIST END */

  //validate messages
  static String valuLesThanOrEqual =
      "Value of must be less than Or equal to"; //32
  static String valueLesThan = "Value of must be less than to"; //32
  static String valuGreaterThanOrEqual =
      "Value of must be greater than Or equal to"; //32
  static String valuGreaterThan = "Value of must be greater than to"; //32
  static String valuEqual = "Value of must be equal to"; //32
  static String plsSelectIn = "Please select value in"; //32
  static String valuLenLessOrEqual =
      "Value of length must be less than Or equal to"; //32
  static String valuLenGreaterOrEqual =
      "Value of length must be greater than Or equal to"; //32
  static String valuLenEqual = "Value of length must be equal to"; //32
  static String wesUsageGraterQuatOpen =
      "Sum of Usage and Wastage cannot be more than the sum of Quantity Received and Opening Stock"; //32
  static String PleaseEnterValueIn = "Please enter value in"; //32
  static String PleaseSelectAfterTimeIn = "Please select time after in"; //32
  static String PleaseSelectAfterDateIn = "Please select date after in"; //32
  static String PleaseSelectBeforTimeIn = "Please select time before in"; //32
  static String PleaseSelectBeforDateIn = "Please select date before in"; //32
  static String PleaseSelectBeforTimeInIsValidTime =
      "Please select is valid time in"; //32
  static String leavingLesThanjoining =
      "Date of Leaving should be less than date of joining";
  static String plsEnter = "Please enter value"; //32
  static String plsFill = "Please fill value"; //32
  static String plsSelect = "Please select value"; //32
  static String valuBefore = "Value of must be before"; //32
  static String valuAfter = "Value of must be after"; //32
  static String futureDateNotAllowed =
      "Future date is not allowed in follow up visit date"; //32
  static String selecisChildavail = "Please select Is child available?"; //32
  static String meetingAlredExist =
      "A meeting already exist on this selected date"; //32

// Growth Monitoring Validate messages
  static String plsSelectMesureEquip = "Please select Measurement Equipment!";
  static String plsSelectHeight = "Please enter measurement height!";
  static String plsSelectWeight = "Please enter  measurement weight!";
  static String plsSelectMesureDate = "Please enter  measurement taken date!";
  static String pleaseSelectMeasurementTaken = "Please enter  measurement taken";
  static String plsSelectreason = "Please select Reason!";
  static String reEnter = "Re Enter";
  static String updateMeasurement = "Child measurement";
  static String ChildIsNotAppilcableForExitToday = "Child is not applicable for exit today";
  static String January ="January";
  static String February = "February";
  static String March =  "March";
  static String April =  "April";
  static String May =  "May";
  static String June =   "June";
  static String July = "July";
  static String August =  "August";
  static String September =  "September";
  static String October =  "October";
  static String November =  "November";
  static String December = "December";
}
